#RewardsTime config

#Log extra details
log: false

#Enable rewards for different activities
rewards:
    craft: true
    smelt: true
    block: true
    mob: true
    vote: true
    
#Enable bonus rewards
bonus:
    mobarmor: true
    tool: true

#Enable rewards in these gamemodes
gamemodes:
    survival: true
    creative: false
    adventure: true

#Number of seconds to wait before notifying players of their gains    
rewardtime: 300

#Number of seconds to wait after entity is damaged before resetting its damage table
damagetimeout: 60

#Number of minutes to wait between auto saving vote counts
votesaveminutes: 15

#Crafting rewards
# Format - 
# item_name[/metadata]:
#   money: reward_money
# Warning: Items that can be repeatedly crafted such as iron <> ironblocks can be exploited
craft:
    iron_pickaxe:
        money: 4

#Smelting rewards
# Note: smelting does not support metadata        
smelt:
    iron_ingot:
        money: 1

#Block mining rewards
# Metadata is supported
# Warning: While the player will not get rewards for blocks that drop themselves,
#   blocks that drop a different item that can be placed to get the block back
#   (Such as sugarcane) can be exploited
block:
    diamond_ore:
        money: 10


#Rewards for voting
#Note: "every" and "achieve" can only go up to 2^31 (2.147 billion)
#Note: You will only recieve 1 reward for voting: 
#   If the achieve list contains a reward for your count, it will be that one.
#   Otherwise it will be the highest in the every list.

votes:
    every:
        '1':
            money: 500
            broadcast: "&c<player>&f has voted and recieved &9$<money>"
    achieve:
        '1':
            money: 1000
            broadcast: "&c<player>&f has voted for the first time and recieved &9$<money>"

# Default mobarmor bonuses
# Type can be:
#   - multiply: Multiplies amount by value
#   - add: Adds amount to value
mobarmor:
    material:
        diamond:
            type: multiply
            bonus: 4
        gold:
            type: multiply
            bonus: 3
        iron:
            type: multiply
            bonus: 3
        leather:
            type: multiply
            bonus: 1
        chainmail:
            type: multiply
            bonus: 2
        other:
            type: multiply
            bonus: 1
    type:
        helmet:
            type: add
            bonus: 1
        chestplate:
            type: add
            bonus: 3
        leggings:
            type: add
            bonus: 2
        boots:
            type: add
            bonus: 1

# Default tool bonuses (bonus rewards for mining blocks with certain tools)
tool:
    enchant:
        silk_touch:
            type: multiply
            bonus: 0
        loot_bonus_blocks/1:
            type: multiply
            bonus: 2
        loot_bonus_blocks/2:
            type: multiply
            bonus: 3
        loot_bonus_blocks/3:
            type: multiply
            bonus: 4

#Rewards for killing mobs
# Format -
# mob_name:
#   money: reward_money
#   items: item_name/[metadata]/maxdrops/changeperdrop%,item_name/[metadata]/maxdrops/chanceperdrop%,...
mob:
    creeper:
        money: 5
        items: diamond_sword//2/0.05
        exp: 10
    zombie:
        money: 2
    chicken:
        money: 1
    skeleton:
        money: 5
    spider:
        money: 3
    giant:
        money: 25
    slime:
        money: 1
    ghast:
        money: 20
    pig:
        money: 1
    pig_zombie:
        money: 4
    enderman:
        money: 8
    cave_spider:
        money: 5
    silverfish:
        money: 3
    blaze:
        money: 5
    magma_cube:
        money: 5
    ender_dragon:
        money: 2500
    wither:
        money: 1500
    bat:
        money: 1
    witch:
        money: 15
    sheep:
        money: 1
    cow:
        money: 1
    squid:
        money: 1
    wolf:
        money: 3
    mushroom_cow:
        money: 3
    snowman:
        money: 0
    ocelot:
        money: 1
    iron_golem:
        money: 10
    horse:
        money: 2
    villager:
        money: -1
    ender_crystal:
        money: 3