#RewardsTime config

#Log extra details
log: false

#Enable rewards from killing mobs
mobrewards: true

#Enable rewards from mining blocks
blockrewards: true

#Enable rewards from crafting items
craftrewards: true

#Enable rewards from smelting items
smeltrewards: true

#Enable rewards from voting
voterewards: true

#Enable players in creative mode getting rewards
rewardcreative: false

#Enable bonus rewards for killing mobs wearing armor
mobarmorbonus: true

#Crafting rewards
# Format - 
# item_name[/metadata]:
#   money: reward_money
craft:
    iron_pickaxe:
        money: 4

#Smelting rewards
# Note: smelting does not support metadata        
smelt:
    iron_ingot:
        money: 1

#Block mining rewards
# Metadata is supported  
block:
    diamond_ore:
        money: 10


# Default mobarmor bonuses
# Type can be:
#   - multiply: Multiplies amount by value
#   - add: Adds amount to value
mobarmor:
    material:
        diamond:
            type: multiply
            bonus: 4
        gold:
            type: multiply
            bonus: 3
        iron:
            type: multiply
            bonus: 3
        leather:
            type: multiply
            bonus: 1
        chainmail:
            type: multiply
            bonus: 2
        other:
            type: multiply
            bonus: 1
    type:
        helmet:
            type: add
            bonus: 1
        chestplate:
            type: add
            bonus: 3
        leggings:
            type: add
            bonus: 2
        boots:
            type: add
            bonus: 1

#Rewards for killing mobs
# Format -
# mob_name:
#   money: reward_money
mob:
    creeper:
        money: 5
    zombie:
        money: 2
    chicken:
        money: 1
    skeleton:
        money: 5
    spider:
        money: 3
    giant:
        money: 25
    slime:
        money: 1
    ghast:
        money: 20
    pig:
        money: 1
    pig_zombie:
        money: 4
    enderman:
        money: 8
    cave_spider:
        money: 5
    silverfish:
        money: 3
    blaze:
        money: 5
    magma_cube:
        money: 5
    ender_dragon:
        money: 250
    wither:
        money: 150
    bat:
        money: 1
    witch:
        money: 15
    sheep:
        money: 1
    cow:
        money: 1
    squid:
        money: 1
    wolf:
        money: 3
    mushroom_cow:
        money: 3
    snowman:
        money: 0
    ocelot:
        money: 1
    iron_golem:
        money: 10
    horse:
        money: 2
    villager:
        money: 0
    ender_crystal:
        money: 3