name: "RewardsTime"
version: "1.1.2"
author: "ithinkrok"
main: me.ithinkrok.rewardstime.RewardsTime
depend: [Vault]
softdepend: [Votifier]
description: "A plugin for getting rewards from mobs/blocks/crafting/voting"
commands:
    rewardstime:
        description: Useful plugin commands
        permission: rewardstime.command
        usage: "Unexpected arguments. Type /rewardstime to see options"
permissions:
    rewardstime.*:
        default: op
        children:
            rewardstime.command: true
            rewardstime.set: true
            rewardstime.get: true
            rewardstime.reload: true
            rewardstimr.rewards: true
    rewardstime.command:
        default: true
    rewardstime.set:
        default: op
    rewardstime.get:
        default: op
    rewardstime.reload:
        default: op
    rewardstime.rewards:
        default: true