name: "RewardsTime"
version: "0.0.1"
author: "ithinkrok"
main: me.ithinkrok.rewardstime.RewardsTime
depend: [Vault]
description: "A plugin for getting rewards from mobs/blocks/crafting/voting"
commands:
    rewardstime:
        description: Useful plugin commands
        permission: rewardstime.command
        usage: "Type /rewardstime to see options"
permissions:
    rewardstime.*:
        default: op
        children:
            rewardstime.command: true
    rewardstime.command:
        default: op